### ISSUE TITLE
Improve declaration intellisense

### ISSUE THREAD

**Issue by EmNudge** [UltimatePro-Grammer/wati#2]
For the declarations `table`, `elem`, `data`, `type`, `loop`, and `block` we get "unknown" when hovering over labels.
![image](https://github.com/NateLevin1/wati/assets/24513691/ab6628d1-f500-4906-8bb0-3367d41302db)
This is contrast to function declarations where we get a quick summary of what the label points to.
<img width="342" alt="image" src="https://github.com/NateLevin1/wati/assets/24513691/b7a010c6-9401-48d8-b35c-2f3662702aca">
This means when referencing a label later in the file, it's not always obvious what kind of label we're dealing with (if named improperly).

**Comment by NateLevin1** [comment]
Interesting - loop and block not showing hover information sounds like a bug. The others currently aren't handled (although they of course should be!)

In fact, it might be worth it to move from the current "giant regex" approach to an actual parser like [`@webassemblyjs/wast-parser`](https://www.npmjs.com/package/@webassemblyjs/wast-parser) for these features. I'm willing to implement this but I'm not sure when I'll have the time.

**Comment by EmNudge** [comment]
Yeah, a parser is definitely the right approach here. I tried the regex approach myself and missed a bunch of corner cases. 

My schedule is going to be super busy the next few days, but I should be clear the end of the week to start working on these myself. I'd just like to get the docs changes merged before I start work on the more technical features.

**Comment by EmNudge** [comment]
Looks like [@webassemblyjs/wast-parser](https://www.npmjs.com/package/@webassemblyjs/wast-parser) does not have support for reference types and likely many more upcoming wasm features. This makes it a no-go for feature development. Our language server should not fully break when it sees new syntax. It should act more like a syntax highlighter where tokens are preserved, not parsed. 

Something like [@codemirror/lang-wast](https://github.com/codemirror/lang-wast/tree/main) might be able to work. Even though it's meant as a syntax highlighter, we could probably extract the internal parser and use it for tokenization. 

It's based off of [lezer](https://github.com/lezer-parser/lr) which uses incremental parsing (again, perfect for our use case). We could also just clone the grammar file and build it ourself.

**Comment by NateLevin1** [comment]
You are right, something incremental would be ideal (well, required). Implementing that could be a huge undertaking though - if you’re interested, by all means go for it!
